# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

# command to install dependencies
install: pip install -r dev-requirements.txt --use-mirrors

# command to run tests, e.g. python setup.py test
script:
  - tox

env:
  - TOXENV=py27
